### PR TITLE
Huge optimizations, UI improvments

### PR DESCRIPTION
**Pull request by threethan**
I'm working on my own fork of your fork of PiLauncher. I figured I'd PR it before I make any breaking changes.

This commit includes UI updates to all popup menus. I've added text to things, but that also means untranslatable strings.

It defers icon loading (as well as update checking & blur rendering) to speed up the initial app launch.
_Note that this leads to icons populating on-by-one, which might not be desirable._

Not sure if you'll want to make these changes, but take a look and consider. I'll release a build on my own repo once I change a few more things.

### CODE REVIEW

**Comment by threethan** [comment]
Closing the PR because the updater can cause crashes

**Comment by ptrpaws** [comment]
Just verified it works well on Quest Pro, Quest 2, Pico 4 and HTC Vive Focus 3.
I like the changes you did to the ui, especially the smi transparent background for app icons that aren't fully sized, I had some staged code that used palette api to set the background color to the dominant color and I like this more.
Before I merge this I'll translate the strings also your updater patches are def broken.

edit: oops you closed it while I was writing this

**Comment by threethan** [comment]
I'll reopen if you want to fix it yourself haha

**Comment by ptrpaws** [comment]
> I'll reopen if you want to fix it yourself haha
thanks!

btw. do you have any idea how to fix the icons cutting off on the sides?
com oculus shellenv-20230521-204507

**Comment by threethan** [comment]
Odd, I haven't noticed that. Maybe just add a little padding to the app drawables?

**Comment by ptrpaws** [comment]
Good idea, fyi I've almost finished all translations

**Comment by ptrpaws** [comment]
that shoud be it, still need to fix the cut off icons, but I'll do that outside of this pr.
thanks again!

**Comment by ptrpaws** [comment]
fyi "this" was the issue with the update detector

https://github.com/basti564/DreamGrid/commit/cf47981938f9cf39e09a4f96e7ab943632e99aac

**Pull request merged**
